### ISSUE TITLE
NSubstitute version

### ISSUE THREAD

**Issue by chilli-andrew** [scott-xu/EntityFramework.Testing#11]
I have been trying out EntityFramework.Testing.NSubstitute.  It was very easy to get up and running and my tests work great in Visual Studio.  The tests however, fail when run on the build server.  It appears that EntityFramework.Testing.NSubstitute requires NSubstitute 1.8.1.0.  The latest version of NSubstitute is now v1.8.2.0.  I have reverted to using the older version of NSubstitute for now but was wondering if there were any plans to upgrade EntityFramework.Testing.NSubstitute to work with the latest version of NSubstitute?

**Comment by scott-xu** [comment]
You can try bindingRedirect

**Comment by huan086** [comment]
NSubstitute is at version 2.0.2 now. Would be great to update the version restriction

**Comment by lpa-vadim-zaslavsky** [comment]
Hi, this should be solved by #23
