### ISSUE TITLE
FakeItEasy version

### ISSUE THREAD

**Issue by behm** [scott-xu/EntityFramework.Testing#17]
I went back to a project and while upgrading packages I noticed that the **EntityFramework.Testing.FakeItEasy** NuGet package does support the latest version of FakeItEasy which is currently v2.2.0?  

Are their plans to support versions of FakeItEasy > 2.0.0?

**Comment by kpstolk** [comment]
FakeItEasy is currently at 2.3.2 already, no plans to update or remove restriction (if possible)?

**Comment by adamralph** [comment]
Note that FakeItEasy 3.0.0 is due out very soon too.

**Comment by SonOfPirate** [comment]
+1 up-vote for this issue!

**Comment by adamralph** [comment]
FYI FakeItEasy has been in 3.x range (with breaking changes from 2.x) for over 4 months now. Our next release will be 4.0 (with more breaking changes) and due is fairly soon.

**Comment by behm** [comment]
While testing the latest update I have run into the following issue in my sample code when I use any version of FakeItEasy >= 4.0.0.  FakeItEasy v3.4.2 works fine.

> Test Name:	GetAll_ReturnsAllProducts
Test FullName:	FakeItEasyTestingDemo.Tests.ProductServiceTests.GetAll_ReturnsAllProducts
Test Source:	C:\Repos\EntityFrameworkTestingDemo\FakeItEasyTestingDemo.Tests\ProductServiceTests.cs : line 21
Test Outcome:	Failed
Test Duration:	0:00:00.6433162

Result StackTrace:	
at FakeItEasy.FakeItEasyDbSetExtensions.SetupData[TEntity](DbSet`1 dbSet, ICollection`1 data, Func`2 find)
   at FakeItEasyTestingDemo.Tests.ProductServiceTests.GetAll_ReturnsAllProducts() in C:\Repos\EntityFrameworkTestingDemo\FakeItEasyTestingDemo.Tests\ProductServiceTests.cs:line 31
Result Message:	
Test method FakeItEasyTestingDemo.Tests.ProductServiceTests.GetAll_ReturnsAllProducts threw exception: 
System.MissingMethodException: Method not found: 'FakeItEasy.Configuration.IAfterCallSpecifiedWithOutAndRefParametersConfiguration FakeItEasy.Configuration.IReturnValueConfiguration`1.ReturnsLazily(System.Func`2<FakeItEasy.Core.IFakeObjectCall,!0>)'.

Here is an example of one of my tests.
`		[TestMethod]
		public void GetAll_ReturnsAllProducts()
		{
			//Arrange
			var data = new List<Product>
			{
				new Product { Id = 1, Name = "Widget", InStock = true },
				new Product { Id = 2, Name = "Gadget", InStock = true },
				new Product { Id = 3, Name = "Thingy", InStock = true },
				new Product { Id = 4, Name = "Whirlyjig", InStock = true },
			};

			var set = A.Fake<DbSet<Product>>(o => o.Implements(typeof(IQueryable<Product>)).Implements(typeof(IDbAsyncEnumerable<Product>))).SetupData(data);

			var context = A.Fake<AcmeContext>();
			A.CallTo(() => context.Products).Returns(set);

			IProductService service = new ProductService(context);

			//Act 
			var results = service.GetAll();

			//Assert
			Assert.AreEqual(2, results.Count());
		}
`

**Comment by Ouro17** [comment]
Any update on this? Run into the same issue as @behm.

**Comment by scott-xu** [comment]
1.2.2 releases just now.
