### ISSUE TITLE
[Question] EF Core?

### ISSUE THREAD

**Issue by fkubis** [scott-xu/EntityFramework.Testing#24]
Does this work for Entity Framework Core?

**Comment by scott-xu** [comment]
No

发自我的 iPhone

在 2017年8月23日，00:57，Frank <notifications@github.com<mailto:notifications@github.com>> 写道：


Does this work for Entity Framework Core?

**Comment by michael-freidgeim-webjet** [comment]
Do you have any plans to target Core/Standard ?
