### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by msnelling** [scott-xu/EntityFramework.Testing#25]
Hi,
Thanks for this great library, we use it a lot in our EF6 projects. We also use NSubstitute and would like to upgrade this to version >=2.0 which is incompatible with the current version of this library. I can see you've committed a patch to fix this dependency (https://github.com/scott-xu/EntityFramework.Testing/commit/a9a74564fd1d49cf4bdcfe77fbfa6df6e6b8e8d3), when do you expect to release a new version of the library to NuGet.org?

**Comment by scott-xu** [comment]
Just release 1.2.1
