### ISSUE TITLE
Entry(existingobject).CurrentValues throws exception

### ISSUE THREAD

**Issue by btrepp** [scott-xu/EntityFramework.Testing#3]
I have some code in a repository pattern class like this

```
var existing = this.Find(id); //find returns an instance of MyClass or null
if(existing!=null){
    this._context.Entry(existing).CurrentValues.SetValues(newvalues);
}
```

which throws

```
 Member 'CurrentValues' cannot be called for the entity of type 'MyClass' because the entity does not exist in the context. To add an entity to the context call the Add or Attach method of DbSet<MyClass>
```

I get the impression from examples that this code should work. I think its failing because the mocked DbContext/Dbsets don't work 100% the same as the actually entity framework implementations. Entry correctly pulls out the DbEntity, but it's not actually in the tracked objects?.

Entity framework is currently the bane of my existence when it comes to testing code :(

**Comment by git-youzer** [comment]
I think it's because the "existing" MyClass entity is implementing a proxy class when generated using Moq.  this._context.Entry(existing) will not attach your proxy class entity because it's not a type recognized by the context.
