### ISSUE TITLE
NSubstitue 4 support

### ISSUE THREAD

**Issue by peterszekeli** [scott-xu/EntityFramework.Testing#30]
I got the following error if I upgrade to NSubstitute 4.0 and try to use the sample code to set up a fake dbset.

>System.MissingMethodException Method not found: 'System.__Canon NSubstitute.Arg.Any()'. NSubstitute.NSubstituteDbSetExtensions.SetupData[TEntity](DbSet'1 dbSet, ICollection'1 data, Func'2 find)

Note, this is also posted as a question on [StackOverflow](https://stackoverflow.com/questions/55335642/mock-ef-dbcontext-async-methods-using-nsubstitute-4-0).

**Comment by Saulzi** [comment]
This is really easy to add, 

needs to be built against a more recent version on NSub i.e. 4.0 and then it works.
