### ISSUE TITLE
Request support for Entity Framework 6.3 on .netstandard 2.1

### ISSUE THREAD

**Issue by penfold** [scott-xu/EntityFramework.Testing#35]
An update to EF has been released with .net core 3 to allow a .net framework to .net core migration path.

Please, can we have a release that supports EF 6.3 on .net standard?

A quick look at the code base look like there is a need to update the reflection logic in InMemoryAsyncQueryProvider to handle .net core.

**Comment by scott-xu** [comment]
Done
